version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: MitigiaPass
      MYSQL_DATABASE: Mitigia
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb